# global
ssh_private_key_path: ../../key/iam2.pem

# for vagrant
ssh_keypair_name: iam2 
ssh_username: cumulo
access_key_id: AKIAJNRC4UZDVQJZZGBQ
secret_access_key: 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
instance_type: m1.small
region: ap-northeast-1
ami: ami-0541d304
add_host_sh_path: ../etc/add_user.sh
chef_home: ../../chefrepo

# for capistrano
git_host: 172.21.245.155
