# global
ssh_private_key_path: ../../key/

# for vagrant
ssh_keypair_name:  
ssh_username: isucon 
access_key_id: 
secret_access_key: 
instance_type: m1.micro
region: ap-northeast-1
ami: 
add_host_sh_path: ../etc/add_user.sh
chef_home: ../../chefrepo

# for capistrano
git_host: github.com
deploy_to_host: 

